mlmodels/urls.py
from django.contrib import admin
from django.urls import path
from .views import MlModelView

app_name = "mlmodels"

urlpatterns = [
    path('', MlModelView.as_view(), name="mlmodel"),
]

server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mlmodels.urls", namespace="mlmodels")),
]

mlmodels/models.py
from django.db import models

# Create your models here.

mlmodels/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
from .source.logreg import MlModel
class MlModelView(TemplateView):

    template_name = "mlmodels/home.html"
    def get(self, request):
        news = "hello" #request.data.get("news")

        return render(request,self.template_name,{"resp": news})

    def post(self, request):
        news = request.POST.get("news")
        model = MlModel()
        resp = model.predict(news)
        return render(request,self.template_name,{"resp": resp})

mlmodels/templates/mlmodels/header.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Ml {% endblock %}
    </title>
    {% block meta %}
    <meta name="Description" content="Ecom Assignment in Django" />
    {% endblock %}
    <!-- <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5"> -->
    <meta name="apple-mobile-web-app-title" content="ongko">
    <meta name="application-name" content="ongko">
    <meta name="msapplication-TileColor" content="#b91d47">
    <meta name="theme-color" content="#ffffff">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'core/core.css' %}" />
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.0/nouislider.min.js"
        integrity="sha512-UOJe4paV6hYWBnS0c9GnIRH8PLm2nFK22uhfAvsTIqd3uwnWsVri1OPn5fJYdLtGY3wB11LGHJ4yPU1WFJeBYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script src="//polyfill.io/v3/polyfill.min.js?features=es6"></script>


    <!-- Global site tag (gtag.js) - Google Analytics -->


</head>

<body>
    {% include 'mlmodels/navbar.html' %}
    {% block content %}

    {% endblock %}
</body>

mlmodels/templates/mlmodels/home.html
{% extends "mlmodels/header.html" %}
{% load static %}
{% block content%}

<body>
    <div class="container">
        <div class="flexColumn">

            <div class="flexRow centeredBox">
                <h3>Search Results</h3>
            </div>

            <div class="row">
                <form method="POST" action="{% url 'mlmodels:mlmodel' %}" class="col s12">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <textarea name="news" id="textarea1" class="materialize-textarea"></textarea>
                            <label for="textarea1">Textarea</label>
                        </div>
                    </div>
                    <button class="btn" type="submit">submit</button>
                </form>
            </div>
            <div class="flexColumn">
                {{resp}}
            </div>

        </div>
</body>
{% endblock %}

mlmodels/templates/mlmodels/navbar.html
{% block content %}
<nav class="navColor">
    <div class="nav-wrapper">
        <a href="{% url 'mlmodels:mlmodel' %}" class="brand-logo logo center">Stock Sentiment</a>


    </div>
</nav>
{% endblock %}